"""Utilities for Generating Ads."""

def clean(text: str) -> str:
    "Clean text generated by gpt."
    return text.strip(' "\n')

def create_dict(output: str) -> dict | None:
    "create dict out of generated text"
    out_clean = clean(output).split('|')
    if len(out_clean) < 3:
        return None
    ad_dict = {
        "headline": clean(out_clean[0]),
        "short": clean(out_clean[1]),
        "text": clean(out_clean[2])
    }

    return ad_dict
        
    
    
